package com.qiji.cps.module.cps.mcp.security;

import com.qiji.cps.framework.common.mcp.McpIdentityClaims;
import com.qiji.cps.framework.common.mcp.McpIdentityEnvelope;
import com.qiji.cps.framework.tenant.core.context.TenantContextHolder;
import com.qiji.cps.module.ai.framework.ai.config.QijiAiProperties;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.MessageDigest;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;

/**
 * Verifies short-lived identity envelopes generated by the dedicated self-MCP client.
 */
@Service
public class CpsMcpIdentityVerifier {

    private final QijiAiProperties properties;
    private final CpsMcpNonceStore nonceStore;
    private final Clock clock;

    @Autowired
    public CpsMcpIdentityVerifier(QijiAiProperties properties, CpsMcpNonceStore nonceStore) {
        this(properties, nonceStore, Clock.systemUTC());
    }

    CpsMcpIdentityVerifier(QijiAiProperties properties, CpsMcpNonceStore nonceStore, Clock clock) {
        this.properties = properties;
        this.nonceStore = nonceStore;
        this.clock = clock;
    }

    /**
     * Validates the envelope completely before consuming its nonce. No untrusted claims are returned.
     */
    public McpIdentityClaims verify(McpIdentityEnvelope envelope) {
        try {
            QijiAiProperties.McpSelfTest selfTest = requiredSelfTest();
            String secret = requiredText(selfTest.getSecret());
            String clientName = requiredText(selfTest.getClientName());
            if (envelope == null || envelope.payload() == null || envelope.payload().isBlank()
                    || envelope.signature() == null || envelope.signature().isBlank()) {
                throw denied();
            }
            McpIdentityClaims claims = McpIdentityClaims.fromCanonicalPayload(envelope.payload());
            if (!claims.toCanonicalPayload().equals(envelope.payload())) {
                throw denied();
            }
            String expectedSignature = hmacSha256(envelope.payload(), secret);
            if (!MessageDigest.isEqual(expectedSignature.getBytes(StandardCharsets.US_ASCII),
                    envelope.signature().getBytes(StandardCharsets.US_ASCII))) {
                throw denied();
            }
            if (!clientName.equals(claims.clientName())) {
                throw denied();
            }
            Long currentTenantId = TenantContextHolder.getTenantId();
            if (currentTenantId != null && !currentTenantId.equals(claims.tenantId())) {
                throw denied();
            }
            Instant now = clock.instant();
            if (claims.issuedAt().isAfter(now) || !claims.expiresAt().isAfter(now)) {
                throw denied();
            }
            Duration remainingTtl = Duration.between(now, claims.expiresAt());
            if (nonceStore == null || !nonceStore.consume(claims.nonce(), remainingTtl)) {
                throw denied();
            }
            return claims;
        } catch (SecurityException exception) {
            throw exception;
        } catch (RuntimeException exception) {
            // Deliberately do not include envelope or claim values in the error/log output.
            throw denied();
        }
    }

    private QijiAiProperties.McpSelfTest requiredSelfTest() {
        if (properties == null || properties.getMcp() == null || properties.getMcp().getSelfTest() == null
                || !properties.getMcp().getSelfTest().isEnabled()) {
            throw denied();
        }
        return properties.getMcp().getSelfTest();
    }

    private static String requiredText(String value) {
        if (value == null || value.isBlank()) {
            throw denied();
        }
        return value;
    }

    private static String hmacSha256(String payload, String secret) {
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
            return Base64.getUrlEncoder().withoutPadding().encodeToString(
                    mac.doFinal(payload.getBytes(StandardCharsets.UTF_8)));
        } catch (GeneralSecurityException exception) {
            throw denied();
        }
    }

    private static SecurityException denied() {
        return new SecurityException("MCP self-test identity is invalid");
    }

}
