name: qiji-system

services:
  mysql:
    container_name: qiji-mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ruoyi-vue-pro}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - mysql:/var/lib/mysql/
      - ../../sql/mysql/ruoyi-vue-pro.sql:/docker-entrypoint-initdb.d/ruoyi-vue-pro.sql:ro

  redis:
    container_name: qiji-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  server:
    container_name: qiji-server
    build:
      context: ../../qiji-server/
    image: qiji-server
    restart: unless-stopped
    ports:
      - "48080:48080"
    environment:
      # https://github.com/polovyivan/docker-pass-configs-to-container
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS:
        ${JAVA_OPTS:-
          -Xms512m
          -Xmx512m
          -Djava.security.egd=file:/dev/./urandom
        }
      ARGS:
        --spring.datasource.dynamic.datasource.master.url=${MASTER_DATASOURCE_URL:-jdbc:mysql://qiji-mysql:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
        --spring.datasource.dynamic.datasource.master.username=${MASTER_DATASOURCE_USERNAME:-root}
        --spring.datasource.dynamic.datasource.master.password=${MASTER_DATASOURCE_PASSWORD:-123456}
        --spring.datasource.dynamic.datasource.slave.url=${SLAVE_DATASOURCE_URL:-jdbc:mysql://qiji-mysql:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
        --spring.datasource.dynamic.datasource.slave.username=${SLAVE_DATASOURCE_USERNAME:-root}
        --spring.datasource.dynamic.datasource.slave.password=${SLAVE_DATASOURCE_PASSWORD:-123456}
        --spring.data.redis.host=${REDIS_HOST:-qiji-redis}
    depends_on:
      - mysql
      - redis

  admin:
    container_name: qiji-admin
    build:
      context: ../../..
      dockerfile: backend/script/docker/qiji-ui-admin/Dockerfile
      args:
        VITE_APP_TITLE: ${VITE_APP_TITLE:-AgenticCPS管理系统}
        VITE_BASE_URL: ${VITE_BASE_URL:-}
        VITE_API_URL: ${VITE_API_URL:-/admin-api}
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/}
        VITE_OUT_DIR: ${VITE_OUT_DIR:-dist-prod}
        VITE_APP_TENANT_ENABLE: ${VITE_APP_TENANT_ENABLE:-true}
        VITE_APP_CAPTCHA_ENABLE: ${VITE_APP_CAPTCHA_ENABLE:-true}
        VITE_APP_DOCALERT_ENABLE: ${VITE_APP_DOCALERT_ENABLE:-true}
        VITE_APP_BAIDU_CODE: ${VITE_APP_BAIDU_CODE:-}
    image: qiji-admin
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  mysql:
    driver: local
  redis:
    driver: local
